services:
  - type: web
    name: gfg-scraper
    env: python
    plan: free
    pythonVersion: 3.9
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
